apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-service-deployment
  labels:
    app: apt-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apt-service
  template:
    metadata:
      labels:
        app: apt-service

    spec:
      containers:
        - name: apt-service
          image: brianbwengye/apt-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: apt-service-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: apt-service-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apt-service-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: apt-service-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8081"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apt-service-secrets
                  key: mysql-root-password