apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  type: NodePort
  selector:
    app: configuration-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080