kind: ConfigMap
apiVersion: v1
metadata:
  name: elasticsearch-service-config
data:
  someKey1: value1
  #reference: https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.0.RC1/reference/html/#kubernetes-native-service-discovery

  nextService: elasticsearch-service.default.svc.cluster.local:8080

  elasticsearch: elasticsearch-client.default.svc

  elaticsearchPort: "9300"