apiVersion: v1
kind: Service
metadata:
  name: jwt-authentication-db
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: jwt-authentication-db-port
  selector:
    app: jwt-authentication-db
    tier: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-authentication-db
spec:
  selector:
    matchLabels:
      app: jwt-authentication-db
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jwt-authentication-db
        tier: db
    spec:
      containers:
        - image: mysql:5.6
          name: jwt-authentication-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jwt-authentication-secrets
                  key: mysql-root-password
          ports:
            - containerPort: 3306
              name: jwt-authentication-db-port
          volumeMounts:
            - name: jwt-authentication-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: jwt-authentication-db-persistent-storage
          persistentVolumeClaim:
            claimName: jwt-authentication-pv-claim