apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-authentication-deployment
  labels:
    app: jwt-authentication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jwt-authentication
  template:
    metadata:
      labels:
        app: jwt-authentication

    spec:
      containers:
        - name: jwt-authentication
          image: brianbwengye/jwt-authentication:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: jwt-authentication-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: jwt-authentication-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-authentication-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: jwt-authentication-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8081"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jwt-authentication-secrets
                  key: mysql-root-password